### ISSUE TITLE
Removing the EN CN Flags

### ISSUE THREAD

**Issue by yvesfriend** [yvesfriend/LangSwitcherTrial#1]
So I tried adding a new line for the CSS and also I removed the EN-CN flags but somehow it looks like this on my end. 

![image](https://user-images.githubusercontent.com/18525593/88629921-7443ad00-d0e2-11ea-944e-cad06d081c0e.png)

I tried adding padding/margin css for the langswitcher but the "Logo here" adjusts as well and its no longer aligned. 

Btw sorry Ive reached max reply number. So Im just editing now.

**Comment by pamtbaau** [comment]
It all looks perfectly aligned to me...
![image](https://user-images.githubusercontent.com/5120011/88630025-4c3b5600-d0b0-11ea-8b28-44378797129d.png)


Added a line to show alignment.

By the way, in your copy of 'langswitcher.html.twig', on line 1, you should replace the `<ul>` with a `<div>`

**Comment by pamtbaau** [comment]
As a side note, there is some debate on the internet whether flags should be used. I prefer not to use flags...

- http://www.flagsarenotlanguages.com/blog/best-practice-for-presenting-languages/
- https://www.unitedlanguagegroup.com/blog/inside-design-a-language-selector-is-no-place-for-flags#:~:text=If%20a%20website's%20content%20has,lead%20users%20to%20language%20selection.

**Comment by yvesfriend** [comment]
Hey @pamtbaau I already changed it into a div and its working fine now. Although, the underline indicating which language is Active no longer shows. But I guess the users would know if they're under the English or Chinese version right?

Hmmm I guess youre right. Thanks for the insight. I guess I wont be using flags then to be sure.

**Comment by pamtbaau** [comment]
@yvesfriend As another side note...

I think I would prefer the language switcher to be placed above the menu as intended by the LangSwitcher.

- The menu gets too long, unless you have only a few menu items
- It will wrap on smaller screeen sizes.

**Comment by yvesfriend** [comment]
@pamtbaau Okay Ill take this into consideration should it happen that Id be needing more than 2 translations. Btw for the mobile friendly version, do I need to update anything to make it work?

**Comment by pamtbaau** [comment]
The underline still shows in my site as you can see in my image.

Is there no option in LangSwitcher to not show the current selected language? It is quite obvious if your own language is selected...

**Comment by pamtbaau** [comment]
Yes, you will have to fix the mobile menu.

**Comment by yvesfriend** [comment]
@pamtbaau Thanks so much for the help and for everything. Im relatively new to grav and Im just learning on my own. Ive been stuck on this for weeks now. Finally I can proceed with building other parts. Hopefully in the future when I have questions you'd still be there to give some clarification. 😁

**Comment by pamtbaau** [comment]
Just for the fun of it... Would you mind looking at your initial post and consider how 'clear' the question is?

In my view, you were asking why the language switcher doesn't show up, so that was what I was trying to find out. Only today it appears to be about the layout... not whether it was visible or not.

**Comment by yvesfriend** [comment]
Well actually that's still something I havent resolved. Refer to photo below

![image](https://user-images.githubusercontent.com/18525593/88634234-b243cf80-d0e8-11ea-865d-5398b88950f9.png)

I declared the langswitcher twice. One one line 83 of menu-main.html.twig and one below on line 116 of the same file. But if you see the photo, there's only one visible and thats the declaration on the bottom. There's an instance of langswitcher but its just empty. So Im confused as to why the declaration on line 83 didnt really show. 

![image](https://user-images.githubusercontent.com/18525593/88634541-18305700-d0e9-11ea-929c-8c45aac2db1e.png)

**Comment by pamtbaau** [comment]
The variable `langswitcher` called by the 'langswitcher.html.twig` is empty when called from inside the macro. 

Doing a bit of Googling:
- [How can I access template variable in TWIG macro?](https://stackoverflow.com/a/15177276/4137032)
- The [Twig docs](https://twig.symfony.com/doc/2.x/tags/macro.html)

**Comment by yvesfriend** [comment]
Wow thanks again. Ill be sure to be more clear with my questions from now on. 😅

**Comment by pamtbaau** [comment]
Do you mind if I add a reply to the forum with a summary of both issues and answers?

**Comment by yvesfriend** [comment]
Sure thing! Please and thank you!

**Comment by yvesfriend** [comment]
Hey @pamtbaau its been a while. I need your help again with regard to the navigation concern. Ive updated this repo for the latest code. 

My concern here is that I have a navigation named "Section 1", when I click it,  it should scroll down to the first section. However Im confused as to where this part should be configured perhaps in the twig file? I would want to set the sections where each navigation should scroll down to. Let me know if Im not being specific enough so I can explain more. Thanks! 

![nav](https://user-images.githubusercontent.com/18525593/99041439-e672cb80-25c5-11eb-8c71-350dd59d80c1.gif)

**Comment by pamtbaau** [comment]
@yvesfriend, 
- Please create a new issue for this new and different question.
- You repo does not contain modules for folder `02.etc/`. I cannot test is without child modules.
- You are using ordering number `02` twice.
